### ISSUE TITLE
Linux: Use XDG directory specification

### ISSUE THREAD

**Issue by jovial-snyder** [armand-sauzay/note#11]
Just a small feedback. I noticed that `config.yaml` is already in `$HOME/.config/note` which is good, but the actual notes are located in `$HOME/.note`. Would be nice if **note** checks the XDG env variables like `$XDG_DATA_HOME` (default value `$HOME/.local/share`). https://xdgbasedirectoryspecification.com

Or to put it plainly: I wish that **note** would not clutter my home directory :)

**Comment by armand-sauzay** [comment]
Thanks for the detailed explanation and pointers, makes a lot of sense! Just implemented a fix 🙏
