### ISSUE TITLE
The error with neovim remains

### ISSUE THREAD

**Issue by PutaMadre1337** [armand-sauzay/note#17]
Hello again. I updated the app, but the problem persists. When closing a note in neovim (even if I didn't make any changes), I get the error: Error: error reading input: read /dev/stdin: resource temporarily unavailableexit status 1.

Do you have the same error when using neovim?

My operating system: Arch Linux
Neovim build: LazyVim
Terminal: Kitty

By the way, I decided to fork this app as my Pet-Project and here's what I was able to do:
Main.go:
```go
		case "enter":
			if len(m.notes) > 0 {
				current := m.notes[m.cursor]
				if current.isDir {
					// Start renaming the folder
					m.renaming = true
					m.textInput.SetValue(current.title)
					m.textInput.Focus()
					return m, textinput.Blink
				} else {
					// Only open editor for files
					cmd := exec.Command(m.config.DefaultEditor, current.path)
					cmd.Stdin = os.Stdin
					cmd.Stdout = os.Stdout
					cmd.Stderr = os.Stderr

					if err := cmd.Run(); err != nil {
						fmt.Printf("\nError opening editor: %v\n", err)
					}

					m.updateNotes()
					m.updatePreview()
					return m, tea.ClearScreen
				}
			}
```
If I add an error check for the cmd.Run() function, then I can open the note file several times, but I will also get an error)

**Comment by bennettnw2** [comment]
This error is intermittent for myself. I'll switch the config to to use vim instead, as a temporary work around.
